<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Investment Report - {{ $member->name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #1E3A5F;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #1E3A5F;
            margin: 0;
        }
        .member-info {
            margin-bottom: 20px;
        }
        .member-info p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #1E3A5F;
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .total {
            font-weight: bold;
            font-size: 16px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Investment Report</h1>
        <p>Generated on {{ $generatedAt->format('F d, Y \a\t h:i A') }}</p>
    </div>

    <div class="member-info">
        <h2>Member Information</h2>
        <p><strong>Name:</strong> {{ $member->name }}</p>
        <p><strong>Member Code:</strong> {{ $member->member_code ?? 'N/A' }}</p>
        <p><strong>Phone:</strong> {{ $member->phone ?? 'N/A' }}</p>
        <p><strong>Email:</strong> {{ $member->email ?? 'N/A' }}</p>
    </div>

    <h2>Investment History</h2>
    @if($investments->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Principal Amount</th>
                    <th>Interest Rate</th>
                    <th>Status</th>
                    <th>Notes</th>
                </tr>
            </thead>
            <tbody>
                @foreach($investments as $investment)
                <tr>
                    <td>{{ $investment->start_date ? \Carbon\Carbon::parse($investment->start_date)->format('M d, Y') : 'N/A' }}</td>
                    <td>KES {{ number_format($investment->principal_amount ?? 0, 2) }}</td>
                    <td>{{ $investment->expected_roi_rate ?? 0 }}%</td>
                    <td>{{ ucfirst($investment->status ?? 'active') }}</td>
                    <td>{{ $investment->description ?? '-' }}</td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="total">
                    <td colspan="1"><strong>Total Investments:</strong></td>
                    <td><strong>KES {{ number_format($investments->sum('principal_amount'), 2) }}</strong></td>
                    <td colspan="3"></td>
                </tr>
            </tfoot>
        </table>
    @else
        <p>No investments recorded for this member.</p>
    @endif

    <div class="footer">
        <p>This is an automated report generated by Evimeria System.</p>
        <p>For inquiries, please contact the administration.</p>
    </div>
</body>
</html>

