import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/user.dart';
import '../models/wallet.dart';

class ReceiptService {
  const ReceiptService();

  Future<Uint8List> buildContributionReceipt({
    required ContributionRecord contribution,
    required Wallet wallet,
    required EvUser user,
  }) async {
    final pdf = pw.Document();
    final formatter = NumberFormat.currency(symbol: 'KES ');

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Contribution Receipt',
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 16),
                pw.Text('Member: ${wallet.member?.name ?? user.name}'),
                pw.Text('Wallet ID: ${wallet.id}'),
                pw.Text('Generated for: ${user.email}'),
                pw.SizedBox(height: 24),
                pw.Container(
                  padding: const pw.EdgeInsets.all(16),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey400),
                    borderRadius: pw.BorderRadius.circular(8),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      _entryRow('Amount', formatter.format(contribution.amount)),
                      _entryRow('Source', contribution.source.toUpperCase()),
                      _entryRow('Reference', contribution.reference ?? 'N/A'),
                      _entryRow(
                        'Date',
                        contribution.createdAt != null
                            ? DateFormat('dd MMM yyyy, HH:mm').format(contribution.createdAt!)
                            : 'Pending',
                      ),
                      _entryRow('Status', contribution.status),
                    ],
                  ),
                ),
                pw.SizedBox(height: 24),
                pw.Text(
                  'Verification QR',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 8),
                pw.Container(
                  width: 120,
                  height: 120,
                  child: pw.BarcodeWidget(
                    barcode: pw.Barcode.qrCode(),
                    data: _qrPayload(contribution, wallet),
                  ),
                ),
                pw.Spacer(),
                pw.Text(
                  'Generated by Evimeria on ${DateFormat('dd MMM yyyy HH:mm').format(DateTime.now())}',
                  style: pw.TextStyle(color: PdfColors.grey),
                ),
              ],
            ),
          );
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _entryRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          pw.Text(value),
        ],
      ),
    );
  }

  static String _qrPayload(ContributionRecord contribution, Wallet wallet) {
    return {
      'contribution_id': contribution.id,
      'amount': contribution.amount,
      'wallet_id': wallet.id,
      'member_id': wallet.memberId,
      'reference': contribution.reference,
      'generated_at': DateTime.now().toIso8601String(),
    }.toString();
  }
}

